import os
import logging
from datetime import datetime
from fpdf import FPDF

REPORT_TRANSLATIONS = {
    # 1. Header
    "title": {"en": "AgriNova - Farmer Technology Adoption Report", "ta": "அக்ரிநோவா - விவசாய தொழில்நுட்ப ஏற்றுக்கொள்ளல் அறிக்கை"},
    "farmer": {"en": "Farmer", "ta": "விவசாயி"},
    "district": {"en": "District", "ta": "மாவட்டம்"},
    "generated_on": {"en": "Generated On", "ta": "உருவாக்கப்பட்ட தேதி"},
    "time": {"en": "Time", "ta": "நேரம்"},
    "en": {"en": "English", "ta": "ஆங்கிலம்"},
    "ta": {"en": "Tamil", "ta": "தமிழ்"},

    # 2. Farmer Sections
    "basic_profile": {"en": "1. Basic Profile", "ta": "1. விவசாயியின் அடிப்படை விவரங்கள்"},
    "land_crop": {"en": "2. Land & Crop Details", "ta": "2. நிலம் மற்றும் சாகுபடி விவரங்கள்"},
    "tech_usage_section": {"en": "3. Technology & Digital Usage", "ta": "3. தொழில்நுட்பம் மற்றும் டிஜிட்டல் பயன்பாடு"},
    "financial_risk": {"en": "4. Financial & Risk Profile", "ta": "4. நிதி நிலை மற்றும் இடர் விவரம்"},
    "water_irrigation": {"en": "5. Water & Irrigation Details", "ta": "5. நீர் மேலாண்மை மற்றும் பாசன விவரங்கள்"},

    # Fields
    "name": {"en": "Farmer Name", "ta": "விவசாயியின் பெயர்"},
    "age": {"en": "Age", "ta": "வயது"},
    "gender": {"en": "Gender", "ta": "பாலினம்"},
    "education": {"en": "Education Level", "ta": "கல்வித் தகுதி"},
    "experience": {"en": "Farming Experience", "ta": "விவசாய அனுபவம்"},
    "income": {"en": "Annual Income Range", "ta": "ஆண்டு வருமான வரம்பு"},
    "land_area": {"en": "Land Size", "ta": "நிலத்தின் அளவு"},
    "land_ownership": {"en": "Land Ownership", "ta": "நில உரிமை"},
    "crops": {"en": "Crops Cultivated", "ta": "சாகுபடி செய்யப்படும் பயிர்கள்"},
    "soil_type": {"en": "Soil Type", "ta": "மண்ணின் வகை"},
    "irrigation_source": {"en": "Irrigation Source", "ta": "பாசன நீர் ஆதாரம்"},
    "water_availability": {"en": "Water Availability", "ta": "நீர் இருப்பு நிலை"},
    "technologies_used": {"en": "Technologies Used", "ta": "பயன்படுத்தப்படும் தொழில்நுட்பங்கள்"},
    "schemes_aware": {"en": "Government Schemes Aware Of", "ta": "அறிந்த அரசு திட்டங்கள்"},
    "has_loan": {"en": "Agricultural Loan", "ta": "விவசாயக் கடன் விவரம்"},
    "has_insurance": {"en": "Crop Insurance (PMFBY)", "ta": "பயிர் காப்பீடு (PMFBY)"},
    "savings_habit": {"en": "Savings Habit", "ta": "சேமிப்புப் பழக்கம்"},
    "risk_level": {"en": "Risk Tolerance", "ta": "இடர் சகிப்புத்தன்மை"},

    # 3. Score
    "adoption_score_section": {"en": "Technology Adoption Score", "ta": "தொழில்நுட்பத் தத்தெடுப்பு மதிப்பெண்"},
    "score": {"en": "Score", "ta": "மதிப்பெண்"},
    "category": {"en": "Category", "ta": "பிரிவு"},
    "score_explanation": {"en": "This score represents the farmer’s current adoption of modern agricultural technologies.", "ta": "இந்த மதிப்பெண் விவசாயியின் நவீன தொழில்நுட்பப் பயன்பாட்டு நிலையை குறிக்கிறது."},

    # 4. AI Insights
    "ai_insights": {"en": "AI Insights", "ta": "செயற்கை நுண்ணறிவு (AI) பகுப்பாய்வு"},
    
    # 5. Recommended Technologies
    "recommendations": {"en": "Recommended Technologies", "ta": "பரிந்துரைக்கப்படும் தொழில்நுட்பங்கள்"},
    "cost_label": {"en": "Cost", "ta": "செலவு"},
    "scheme_label": {"en": "Related Scheme", "ta": "தொடர்புடைய திட்டம்"},

    # 6. Crop Recommendations
    "crop_recommendations": {"en": "Crop Recommendations", "ta": "பயிர் பரிந்துரைகள்"},

    # 7. Schemes
    "schemes_title": {"en": "Eligible Government Schemes", "ta": "தகுதியான அரசு திட்டங்கள்"},

    # 8. Summary
    "summary": {"en": "Summary", "ta": "சுருக்கம்"},
    "summary_text": {"en": "Based on the farmer’s responses, implementing the recommended technologies and utilizing government schemes can significantly improve farm productivity.", "ta": "விவசாயி அளித்த தகவல்களின் அடிப்படையில், பரிந்துரைக்கப்பட்ட தொழில்நுட்பங்களையும் அரசு திட்டங்களையும் பயன்படுத்துவதன் மூலம் விளைச்சலை அதிகரிக்க முடியும்."},

    # 9. Footer
    "footer_msg": {
        "en": "Click 'Update Profile' once you are done with your recommendation in your field to check your improved level.",
        "ta": "உங்கள் நிலத்தில் இந்தப் பரிந்துரைகளைச் செயல்படுத்திய பிறகு, உங்கள் மேம்பட்ட நிலையைச் சரிபார்க்க 'சுயவிவரத்தைப் புதுப்பிக்கவும்' என்பதை கிளிக் செய்யவும்."
    },
    "footer_gen": {"en": "Generated by AgriNova AI", "ta": "AgriNova AI மூலம் உருவாக்கப்பட்டது"},

    "na": {"en": "N/A", "ta": "குறிப்பிடப்படவில்லை"},
    "yes": {"en": "Yes", "ta": "ஆம்"},
    "no": {"en": "No", "ta": "இல்லை"},
    "acres": {"en": "Acres", "ta": "ஏக்கர்"},
    "years": {"en": "Years", "ta": "ஆண்டுகள்"},
    "ownership": {"en": "Land Ownership", "ta": "நில உரிமை"},
    "other_tech": {"en": "Other Technology", "ta": "மற்ற தொழில்நுட்பங்கள்"},
    "other_scheme": {"en": "Other Schemes", "ta": "மற்ற திட்டங்கள்"},
    "digital_presence": {"en": "Digital Presence", "ta": "டிஜிட்டல் பயன்பாடு"},
    "borewell_depth": {"en": "Borewell Depth", "ta": "ஆழ்துளை கிணறு ஆழம்"},
    "ft": {"en": "FT", "ta": "அடி"}
}

DISTRICT_MAP_EN = [
    'Ariyalur', 'Chengalpattu', 'Chennai', 'Coimbatore', 'Cuddalore', 'Dharmapuri',
    'Dindigul', 'Erode', 'Kallakurichi', 'Kanchipuram', 'Kanyakumari', 'Karur',
    'Krishnagiri', 'Madurai', 'Mayiladuthurai', 'Nagapattinam', 'Namakkal', 'Nilgiris',
    'Perambalur', 'Pudukkottai', 'Ramanathapuram', 'Ranipet', 'Salem', 'Sivaganga',
    'Tenkasi', 'Thanjavur', 'Theni', 'Thoothukudi', 'Tiruchirappalli', 'Tirunelveli',
    'Tirupathur', 'Tiruppur', 'Tiruvallur', 'Tiruvannamalai', 'Tiruvarur', 'Vellore',
    'Viluppuram', 'Virudhunagar'
]
DISTRICT_MAP_TA = [
    'அரியலூர்', 'செங்கல்பட்டு', 'சென்னை', 'கோயம்புத்தூர்', 'கடலூர்', 'தர்மபுரி',
    'திண்டுக்கல்', 'ஈரோடு', 'கள்ளக்குறிச்சி', 'காஞ்சிபுரம்', 'கன்னியாகுமரி', 'கரூர்',
    'கிருஷ்ணகிரி', 'மதுரை', 'மயிலாடுதுறை', 'நாகப்பட்டினம்', 'நாமக்கல்', 'நீலகிரி',
    'பெரம்பலூர்', 'புதுக்கோட்டை', 'ராமநாதபுரம்', 'ராணிப்பேட்டை', 'சேலம்', 'சிவகங்கை',
    'தென்காசி', 'தஞ்சாவூர்', 'தேனி', 'தூத்துக்குடி', 'திருச்சி', 'திருநெல்வேலி',
    'திருப்பத்தூர்', 'திருப்பூர்', 'திருவள்ளூர்', 'திருவண்ணாமலை', 'திருவாரூர்', 'வேலூர்',
    'விழுப்புரம்', 'விருதுநகர்'
]

VALUE_TRANSLATIONS = {
    # Ownership
    "Owned": "சொந்தமானது", "Leased": "குத்தகை", "Rented": "வாடகை",
    # Categories / Levels
    "High": "மிக அதிகம்", "Moderate": "மிதமானது", "Low": "குறைவு", "Medium": "நடுத்தரம்",
    # Education
    "No Formal": "கல்வி இல்லை", "Primary": "தொடக்க கல்வி", "Middle": "நடுநிலைக் கல்வி",
    "Higher Secondary": "மேல்நிலைக் கல்வி", "HSC": "மேல்நிலைக் கல்வி",
    "12th": "12 ஆம் வகுப்பு", "Diploma": "டிப்ளமோ", "ITI": "ITI",
    "Degree": "பட்டப்படிப்பு", "UG": "பட்டப்படிப்பு",
    "Postgraduate": "முதுகலைப் பட்டம்", "PG": "முதுகலைப் பட்டம்",
    # Crops — common Tamil Nadu crops
    "Paddy": "நெல்", "Sugarcane": "கரும்பு", "Sugar Cane": "கரும்பு",
    "Rice": "அரிசி", "Cotton": "பருத்தி",
    "Banana": "வாழை", "Coconut": "தென்னை", "Tomato": "தக்காளி",
    "Maize": "மக்காச்சோளம்", "Turmeric": "மஞ்சள்", "Chillies": "மிளகாய்",
    "Groundnut": "நிலக்கடலை", "Vegetables": "காய்கறிகள்",
    "Flowers": "மலர்கள்", "Sorghum": "சோளம்", "Millets": "சிறுதானியங்கள்",
    "Ragi": "கேழ்வரகு", "Wheat": "கோதுமை", "Pulses": "பருப்பு வகைகள்",
    "Ginger": "இஞ்சி", "Onion": "வெங்காயம்", "Garlic": "பூண்டு",
    "Spinach": "கீரை", "Brinjal": "கத்திரிக்காய்", "Pepper": "மிளகு",
    "Jasmine": "மல்லிகை", "Marigold": "சாமந்தி", "Rose": "ரோஜா",
    "Mango": "மாம்பழம்", "Guava": "கொய்யா", "Tapioca": "மரவள்ளிக்கிழங்கு",
    # Irrigation methods
    "Borewell": "ஆழ்துளை கிணறு", "Well": "கிணறு", "River": "ஆறு",
    "Canal": "கால்வாய்", "Rainfed": "மழைநீர்",
    "Drip": "சொட்டு நீர்", "Sprinkler": "தெளிப்பு நீர்",
    "Flood": "வெள்ளப் பாசனம்", "Pond": "குளம்", "Tank": "ஏரி",
    # Water Availability
    "Abundant": "ஏராளம்", "Scarce": "பற்றாக்குறை",
    # Soil types
    "Red": "செம்மண்", "Black": "கரிசல் மண்", "Alluvial": "வண்டல் மண்",
    "Clay": "களிமண்", "Sandy": "மணல் மண்", "Loamy": "களிமண் கலந்த",
    "Loam": "களிமண் கலந்த", "Silt": "வண்டல் மண்", "Peaty": "கரிம மண்",
    # Savings / Behavior
    "Regularly": "தவறாமல்", "Occasionally": "எப்போதாவது", "Never": "இல்லை",
    "None": "இல்லை",
    # General Yes/No/Gender
    "Male": "ஆண்", "Female": "பெண்", "Other": "பிற",
    "Yes": "ஆம்", "No": "இல்லை",
    # Technologies used (farmer form values)
    "Drip Irrigation": "சொட்டு நீர் பாசனம்",
    "Sprinkler Irrigation": "தெளிப்பு நீர் பாசனம்",
    "Tractor": "டிராக்டர்",
    "Harvester": "அறுவடை செய்பவர்",
    "DigitalPayment": "டிஜிட்டல் பேமெண்ட்",
    "Digital Payment": "டிஜிட்டல் பேமெண்ட்",
    "Mobile App": "மொபைல் செயலி",
    "Drone": "ட்ரோன்",
    "Drone Spraying": "ட்ரோன் தெளித்தல்",
    "IoT Sensor": "IoT உணரி",
    "Solar Pump": "சூரிய சக்தி பம்ப்",
    "GPS": "GPS",
    "Soil Testing Kit": "மண் பரிசோதனை கிட்",
    "Weather Forecast Mobile App": "வானிலை முன்னறிவிப்பு செயலி",
    "Uzhavan Mobile App": "உழவன் மொபைல் செயலி",
    "Mulching Sheets": "மல்சிங் தாள்கள்",
    "Farm Mechanization Tools": "விவசாய கருவிகள்",
    "Soil Moisture Sensor": "மண் ஈரப்பதம் சென்சார்",
    "Greenhouse / Polyhouse": "பசுமை இல்லம்",
    # Brand
    "AgriNova": "AgriNova",
}

logger = logging.getLogger(__name__)

class PDFReportGenerator:
    def __init__(self):
        current_dir = os.path.dirname(os.path.abspath(__file__))
        self.font_path = os.path.join(current_dir, "..", "NotoSansTamil-Regular.ttf")
        self.tamil_font_registered = os.path.exists(self.font_path)
        
    def _clean_en(self, text):
        if not text: return ""
        # Replace common unicode that crashes Helvetica
        replacements = {"\u2013": "-", "\u2022": "*", "\u20b9": "Rs.", "\u201c": '"', "\u201d": '"', "\u2018": "'", "\u2019": "'"}
        for k, v in replacements.items():
            text = str(text).replace(k, v)
        return text

    def t(self, key, lang):
        val = REPORT_TRANSLATIONS.get(key, {}).get(lang, key)
        return self._clean_en(val) if lang == 'en' else val
    
    def transliterate_name(self, name):
        """Phonetically map English names to Tamil script. Covers 200+ common Tamil names."""
        if not name: return ""
        mapping = {
            # A
            "Arun": "அருண்", "Arjun": "அர்ஜுன்", "Anand": "ஆனந்த்",
            "Ashwin": "அஸ்வின்", "Aravind": "அரவிந்த்", "Arumugam": "ஆறுமுகம்",
            "Arul": "அருள்", "Ajith": "அஜித்", "Anbu": "அன்பு",
            "Amudha": "அமுதா", "Ambika": "அம்பிகா", "Alamelu": "அலமேலு",
            # B
            "Balu": "பாலு", "Babu": "பாபு", "Balamurugan": "பாலமுருகன்",
            "Balaji": "பாலாஜி", "Baskaran": "பாஸ்கரன்",
            # C
            "Chandru": "சந்துரு", "Chandra": "சந்திரா", "Chandrakala": "சந்திரகலா",
            "Chellamuthu": "செல்லமுத்து",
            # D
            "Devi": "தேவி", "Dhana": "தன", "Dhanush": "தனுஷ்",
            "Dinesh": "தினேஷ்", "Durai": "துரை",
            # G
            "Ganesh": "கணேஷ்", "Ganesan": "கணேசன்", "Gopal": "கோபால்",
            "Govindarajan": "கோவிந்தராஜன்", "Guna": "குணா",
            # H
            "Hari": "ஹரி", "Harish": "ஹரிஷ்",
            # I
            "Ilango": "இளங்கோ", "Indhu": "இந்து", "Indira": "இந்திரா",
            # J
            "Jayanthi": "ஜெயந்தி", "Jayalakshmi": "ஜெயலட்சுமி",
            "Jeyaraj": "ஜெயராஜ்", "Jothi": "ஜோதி",
            # K
            "Karthik": "கார்த்திக்", "Karthikeyan": "கார்த்திகேயன்",
            "Kannan": "கண்ணன்", "Kavitha": "கவிதா", "Kumar": "குமார்",
            "Kumari": "குமாரி", "Krishnan": "கிருஷ்ணன்",
            "Kamal": "கமல்", "Kamala": "கமலா", "Kala": "கலா",
            # L
            "Lakshmi": "லட்சுமி", "Lalitha": "லலிதா",
            # M
            "Mani": "மணி", "Manikandan": "மணிகண்டன்",
            "Murugan": "முருகன்", "Murugesan": "முருகேசன்",
            "Muthu": "முத்து", "Muthuraj": "முத்துராஜ்",
            "Meena": "மீனா", "Meenakshi": "மீனாட்சி",
            # N
            "Nandha": "நந்தா", "Nithya": "நித்யா", "Nalini": "நளினி",
            "Nirmala": "நிர்மலா", "Nirmal": "நிர்மல்", "Nandhini": "நந்தினி",
            # P
            "Pandi": "பாண்டி", "Pandian": "பாண்டியன்",
            "Palani": "பழனி", "Palanisamy": "பழனிசாமி",
            "Priya": "பிரியா", "Priyanka": "பிரியங்கா",
            # R
            "Raja": "ராஜா", "Rajesh": "ராஜேஷ்", "Raju": "ராஜு",
            "Ravi": "ரவி", "Ramesh": "ரமேஷ்", "Ramakrishnan": "ராமகிருஷ்ணன்",
            "Ramasamy": "ராமசாமி", "Radha": "ராதா",
            # S
            "Santhosh": "சந்தோஷ்", "Saravanan": "சரவணன்",
            "Selvam": "செல்வம்", "Selvi": "செல்வி",
            "Senthil": "செந்தில்", "Senthilkumar": "செந்தில்குமார்",
            "Shankar": "சங்கர்", "Shanthi": "சாந்தி",
            "Suresh": "சுரேஷ்", "Sudha": "சுதா",
            "Sundaram": "சுந்தரம்", "Sundar": "சுந்தர்",
            "Saraswathi": "சரஸ்வதி", "Saranya": "சரண்யா",
            "Sridhar": "ஸ்ரீதர்", "Sivakumar": "சிவகுமார்",
            "Sivaraman": "சிவராமன்", "Siva": "சிவா",
            # T
            "Tamilarasan": "தமிழரசன்", "Tamilselvan": "தமிழ்செல்வன்",
            "Thangam": "தங்கம்", "Thirumalai": "திருமலை",
            # U
            "Uma": "உமா", "Udhaya": "உதயா",
            # V
            "Velu": "வேலு", "Velmurugan": "வேல்முருகன்",
            "Venkatesh": "வெங்கடேஷ்", "Vijay": "விஜய்",
            "Vijayakumar": "விஜயகுமார்", "Vinoth": "வினோத்",
        }
        # Try full match first
        if name in mapping:
            return mapping[name]
        # Try case-insensitive full match
        name_lower = name.strip().lower()
        for k, v in mapping.items():
            if k.lower() == name_lower:
                return v
        # Try word-by-word
        parts = name.split()
        translated_parts = [mapping.get(p, None) or
                            next((v for k, v in mapping.items() if k.lower() == p.lower()), p)
                            for p in parts]
        result = " ".join(translated_parts)
        # If any part is still English, try GoogleTranslator as final fallback
        if any(p.isascii() and p.isalpha() for p in translated_parts):
            try:
                from deep_translator import GoogleTranslator
                result = GoogleTranslator(source='en', target='ta').translate(name)
            except Exception as e:
                logger.warning(f"Name translation fallback failed for '{name}': {e}")
        return result

    def vt(self, value, lang):
        if not value or str(value).strip().lower() in ['none', 'n/a', 'unknown', '']:
            return "குறிப்பிடப்படவில்லை" if lang == 'ta' else "N/A"
        
        if lang != 'ta':
            val = str(value)
            return self._clean_en(val) if lang == 'en' else val
        
        if isinstance(value, list):
            # Sort out any empty strings from list
            value = [v for v in value if v and str(v).strip()]
            if not value: return "குறிப்பிடப்படவில்லை"
            return ", ".join([self.vt(v, lang) for v in value])
        
        # Try case-insensitive lookup
        lookup = VALUE_TRANSLATIONS.get(str(value))
        if not lookup:
            s_val = str(value).strip().lower()
            for k, v in VALUE_TRANSLATIONS.items():
                if k.lower() == s_val:
                    lookup = v
                    break
        
        if not lookup and lang == 'ta':
            try:
                from deep_translator import GoogleTranslator
                lookup = GoogleTranslator(source='en', target='ta').translate(str(value))
            except Exception as e:
                logger.error(f"Translation failed for {value}: {e}")

        res = lookup or str(value)
        # Handle income ranges or other long strings
        if "₹" in str(res):
            res = str(res).replace("₹", "ரூ. ")
        return res

    def resolve_district(self, district_value, lang):
        if not district_value:
            return ""
        d = str(district_value).strip()
        if d in DISTRICT_MAP_TA:
            idx = DISTRICT_MAP_TA.index(d)
            return DISTRICT_MAP_TA[idx] if lang == 'ta' else DISTRICT_MAP_EN[idx]
        if d in DISTRICT_MAP_EN:
            idx = DISTRICT_MAP_EN.index(d)
            return DISTRICT_MAP_TA[idx] if lang == 'ta' else DISTRICT_MAP_EN[idx]
        return d

    def generate_report(self, farmer_data, user_data, adoption_result, recommendations, schemes, language='en'):
        lang = language if language in ['en', 'ta'] else 'en'
        
        pdf = FPDF()
        # Enable complex script shaping for Tamil
        if lang == 'ta':
            try:
                pdf.set_text_shaping(True, script="taml", language="tam")
            except Exception as e:
                logging.error(f"Failed to enable text shaping: {e}")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pw = pdf.epw
        
        # Setup fonts
        # Avoid hardcoded Linux paths. Use bundled NotoSans font or built-in Helvetica
        current_dir = os.path.dirname(os.path.abspath(__file__))
        local_noto_path = os.path.normpath(os.path.join(current_dir, "..", "NotoSansTamil-Regular.ttf"))
        
        # Register NotoSansTamil if it exists
        has_noto = False
        if os.path.exists(local_noto_path):
            try:
                pdf.add_font("NotoSansTamil", style="", fname=local_noto_path)
                pdf.add_font("NotoSansTamil", style="B", fname=local_noto_path)
                pdf.add_font("NotoSansTamil", style="I", fname=local_noto_path)
                has_noto = True
            except Exception as e:
                logging.error(f"Failed to register NotoSansTamil font: {e}")

        # Choose base font and fallback
        if lang == 'ta' and has_noto:
            base_font = "NotoSansTamil"
            # Add English fallback for English characters in Tamil report
            try:
                arial_path = os.path.join(os.environ.get('WINDIR', 'C:\\Windows'), 'Fonts', 'arial.ttf')
                if os.path.exists(arial_path):
                    pdf.add_font("ArialFallback", style="", fname=arial_path)
                    pdf.set_fallback_fonts(["ArialFallback"])
            except Exception as e:
                logging.error(f"Failed to load fallback font: {e}")
        else:
            # For English, use built-in Helvetica
            base_font = "Helvetica"
            # If we have Tamil font, set it as fallback for any Tamil names in English report
            if has_noto:
                try:
                    pdf.set_fallback_fonts(["NotoSansTamil"])
                except:
                    pass
            
        def set_title():
            pdf.set_font(base_font, 'B', 18)
            pdf.set_text_color(45, 80, 22)
            
        def set_header():
            pdf.set_font(base_font, 'B', 14)
            pdf.set_text_color(74, 124, 44)
            
        def set_body():
            pdf.set_font(base_font, '', 11)
            pdf.set_text_color(0, 0, 0)
            
        def set_footer():
            pdf.set_font(base_font, 'I' if lang=='en' else '', 10)
            pdf.set_text_color(45, 80, 22) # Dark Green for emphasis

        # Date/Time formatting
        now = datetime.now()
        ta_months = {'01':'ஜனவரி','02':'பிப்ரவரி','03':'மார்ச்','04':'ஏப்ரல்','05':'மே','06':'ஜூன்','07':'ஜூலை','08':'ஆகஸ்ட்','09':'செப்டம்பர்','10':'அக்டோபர்','11':'நவம்பர்','12':'டிசம்பர்'}
        if lang == 'ta':
            date_str = f"{now.strftime('%d')} {ta_months.get(now.strftime('%m'))} {now.strftime('%Y')}"
            time_str = f"{now.strftime('%I:%M')} {'காலை' if now.strftime('%p') == 'AM' else 'மாலை'}"
        else:
            date_str = now.strftime('%d %b %Y')
            time_str = now.strftime('%I:%M %p')

        def add_bullet(text):
            set_body()
            pdf.set_x(pdf.l_margin)
            bullet = "  - "
            pdf.multi_cell(pw, 8, bullet + text)

        # 1. Header
        set_title()
        pdf.multi_cell(pw, 10, self.t("title", lang), align='C')
        pdf.ln(5)

        # Quick Overview
        set_body()
        display_name_header = user_data.get('name')
        if lang == 'ta' and display_name_header:
            display_name_header = self.transliterate_name(display_name_header)
        name = display_name_header or self.t('na', lang)
        district = self.resolve_district(user_data.get('district'), lang) or self.t('na', lang)
        pdf.cell(pw/2, 6, f"{self.t('farmer', lang)}: {name}")
        pdf.cell(pw/2, 6, f"{self.t('district', lang)}: {district}", ln=1)
        pdf.cell(pw/2, 6, f"{self.t('generated_on', lang)}: {date_str}")
        pdf.cell(pw/2, 6, f"{self.t('time', lang)}: {time_str}", ln=1)
        pdf.ln(5)

        # Farmer Details Sections
        # ── 1. Basic Profile ──────────────────────────────────────────────────
        set_header()
        pdf.multi_cell(pw, 8, self.t("basic_profile", lang))
        pdf.ln(2)
        display_name = user_data.get('name', '')
        if lang == 'ta':
            display_name = self.transliterate_name(display_name)
        add_bullet(f"{self.t('name', lang)}: {display_name}")
        add_bullet(f"{self.t('age', lang)}: {farmer_data.get('age', self.t('na', lang))}")
        add_bullet(f"{self.t('gender', lang)}: {self.vt(farmer_data.get('gender'), lang)}")
        add_bullet(f"{self.t('education', lang)}: {self.vt(farmer_data.get('education'), lang)}")
        add_bullet(f"{self.t('experience', lang)}: {farmer_data.get('experience', self.t('na', lang))} {self.t('years', lang)}")
        add_bullet(f"{self.t('income', lang)}: {self.vt(farmer_data.get('income'), lang)}")
        pdf.ln(3)

        # ── 2. Land & Crop ────────────────────────────────────────────────────
        set_header()
        pdf.multi_cell(pw, 8, self.t("land_crop", lang))
        pdf.ln(2)
        add_bullet(f"{self.t('land_area', lang)}: {farmer_data.get('land_area', self.t('na', lang))} {self.t('acres', lang)}")
        add_bullet(f"{self.t('land_ownership', lang)}: {self.vt(farmer_data.get('land_ownership'), lang)}")
        add_bullet(f"{self.t('crops', lang)}: {self.vt(farmer_data.get('crops'), lang)}")
        add_bullet(f"{self.t('soil_type', lang)}: {self.vt(farmer_data.get('soil_type'), lang)}")
        pdf.ln(3)

        # ── 3. Tech & Digital ─────────────────────────────────────────────────
        set_header()
        pdf.multi_cell(pw, 8, self.t("tech_usage_section", lang))
        pdf.ln(2)
        techs = farmer_data.get('technologies_used', [])
        add_bullet(f"{self.t('technologies_used', lang)}: {', '.join([self.vt(t, lang) for t in techs]) if techs else self.t('na', lang)}")
        if farmer_data.get('other_technology'):
            add_bullet(f"{self.t('other_tech', lang)}: {farmer_data.get('other_technology')}")
        digital = []
        if farmer_data.get('using_uzhavan_app'): digital.append("உழவன் செயலி" if lang=='ta' else "Uzhavan App")
        if farmer_data.get('watch_agri_youtube'): digital.append("விவசாய யூடியூப்" if lang=='ta' else "Agri YouTube")
        if farmer_data.get('in_whatsapp_groups'): digital.append("வாட்ஸ்அப் குழுக்கள்" if lang=='ta' else "WhatsApp Groups")
        add_bullet(f"{self.t('digital_presence', lang)}: {', '.join(digital) if digital else self.t('na', lang)}")
        pdf.ln(3)

        # ── 4. Financial & Risk ───────────────────────────────────────────────
        set_header()
        pdf.multi_cell(pw, 8, self.t("financial_risk", lang))
        pdf.ln(2)
        add_bullet(f"{self.t('has_loan', lang)}: {self.t('yes' if farmer_data.get('has_loan') else 'no', lang)}")
        add_bullet(f"{self.t('has_insurance', lang)}: {self.t('yes' if farmer_data.get('enrolled_pmfby') else 'no', lang)}")
        add_bullet(f"{self.t('savings_habit', lang)}: {self.vt(farmer_data.get('savings_habit'), lang)}")
        add_bullet(f"{self.t('risk_level', lang)}: {self.vt(farmer_data.get('risk_level'), lang)}")
        pdf.ln(3)

        # ── 5. Water & Irrigation ─────────────────────────────────────────────
        set_header()
        pdf.multi_cell(pw, 8, self.t("water_irrigation", lang))
        pdf.ln(2)
        add_bullet(f"{self.t('irrigation_source', lang)}: {self.vt(farmer_data.get('irrigation_source'), lang)}")
        add_bullet(f"{self.t('water_availability', lang)}: {self.vt(farmer_data.get('water_availability'), lang)}")
        if farmer_data.get('borewell_depth'):
            add_bullet(f"{self.t('borewell_depth', lang)}: {farmer_data.get('borewell_depth')} {self.t('ft', lang)}")
        pdf.ln(5)

        # 3. Adoption Results
        pdf.set_x(pdf.l_margin)
        set_header()
        pdf.multi_cell(pw, 8, self.t("adoption_score_section", lang))
        pdf.ln(2)
        pdf.set_x(pdf.l_margin)
        pdf.set_font(base_font, 'B', 12)
        score_text = f"{self.t('score', lang)}: {adoption_result.get('adoption_score', 0)}% | {self.t('category', lang)}: {self.vt(adoption_result.get('adoption_category', 'N/A'), lang)}"
        pdf.multi_cell(pw, 8, score_text)
        pdf.set_x(pdf.l_margin)
        set_body()
        pdf.multi_cell(pw, 6, self.t("score_explanation", lang))
        pdf.ln(5)

        # 4. AI Insights
        pdf.set_x(pdf.l_margin)
        set_header()
        pdf.multi_cell(pw, 8, self.t("ai_insights", lang))
        pdf.ln(2)
        if lang == 'en':
            add_bullet("Low technology usage detected" if (len(techs) < 2) else "Good technology usage detected")
            add_bullet("Limited awareness of government schemes" if (len(farmer_data.get('schemes_aware', [])) < 2) else "Good awareness of government schemes")
            add_bullet("Significant opportunity to improve yield through the recommendations below.")
        else:
            add_bullet("நவீன தொழில்நுட்பப் பயன்பாடு குறைவாக உள்ளது" if (len(techs) < 2) else "நவீன தொழில்நுட்பப் பயன்பாடு சிறப்பாக உள்ளது")
            add_bullet("அரசுத் திட்டங்கள் குறித்த விழிப்புணர்வு அதிகரிக்கப்பட வேண்டும்" if (len(farmer_data.get('schemes_aware', [])) < 2) else "அரசுத் திட்டங்கள் குறித்த விழிப்புணர்வு சிறப்பாக உள்ளது")
            add_bullet("கீழே பரிந்துரைக்கப்பட்டுள்ள வழிமுறைகளைப் பின்பற்றுவதன் மூலம் மகசூலை கணிசமாக அதிகரிக்க முடியும்.")
        pdf.ln(5)

        # 5. Recommended Technologies (Both Languages)
        pdf.set_x(pdf.l_margin)
        set_header()
        pdf.multi_cell(pw, 8, self.t("recommendations", lang))
        pdf.ln(2)
        tech_list = recommendations.get('technologies', []) if recommendations else []
        if tech_list:
            for t_item in tech_list[:5]:
                name = t_item.get('tech_ta' if lang == 'ta' else 'tech_en', 'N/A')
                desc = t_item.get('description_ta' if lang == 'ta' else 'description_en', '')
                
                add_bullet(name)
                set_body()
                if desc:
                    pdf.set_x(pdf.l_margin + 10)
                    pdf.multi_cell(pw - 10, 6, desc)
                pdf.ln(2)
        else:
            add_bullet(self.t("na", lang))
        pdf.ln(5)

        # 6. Crop Recommendations
        pdf.set_x(pdf.l_margin)
        set_header()
        pdf.multi_cell(pw, 8, self.t("crop_recommendations", lang))
        pdf.ln(2)
        crop_list = recommendations.get('crops', []) if recommendations else []
        if crop_list:
            for c_item in crop_list[:4]:
                name = c_item.get('crop_ta' if lang == 'ta' else 'crop_en', 'N/A')
                add_bullet(name)
        else:
            add_bullet(self.t("na", lang))
        pdf.ln(5)

        # 7. Schemes
        pdf.set_x(pdf.l_margin)
        set_header()
        pdf.multi_cell(pw, 8, self.t("schemes_title", lang))
        pdf.ln(2)
        if schemes:
            for s_item in schemes[:5]:
                name = s_item.get('name_ta') if lang == 'ta' else s_item.get('name')
                add_bullet(name or s_item.get('name', 'N/A'))
        else:
            add_bullet(self.t("na", lang))
        pdf.ln(5)

        # 8. Summary
        pdf.set_x(pdf.l_margin)
        set_header()
        pdf.multi_cell(pw, 8, self.t("summary", lang))
        pdf.ln(2)
        pdf.set_x(pdf.l_margin)
        set_body()
        pdf.multi_cell(pw, 6, self.t("summary_text", lang))
        pdf.ln(10)

        # ── 9. Footer: Follow-up Action ────────────────────────────────────────
        pdf.ln(5)
        set_footer()
        # Message with date
        footer_text = f"{self.t('footer_msg', lang)} ({date_str})"
        pdf.multi_cell(pw, 7, footer_text, align='C')
        pdf.ln(3)
        
        # Generator text with brand name
        brand_name = "அக்ரிநோவா" if lang == 'ta' else "AgriNova"
        gen_text = self.t('footer_gen', lang).replace("AgriNova", brand_name)
        pdf.set_font(base_font, 'I' if lang=='en' else '', 8)
        pdf.multi_cell(pw, 5, gen_text, align='C')

        # Output
        filename = f"AgriNova_Report_{user_data.get('user_id', 'unknown')}_{lang}.pdf"
        filepath = os.path.join('reports', filename)
        os.makedirs('reports', exist_ok=True)
        pdf.output(filepath)
        return filepath

pdf_generator = PDFReportGenerator()
